# Generated by Django 5.1.4 on 2024-12-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumuri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfume_images/'),
        ),
    ]
