# Generated by Django 5.1.4 on 2025-01-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumuri', '0003_remove_perfume_notes_perfume_base_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/'),
        ),
    ]
