# Generated by Django 5.1.4 on 2025-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumuri', '0005_alter_review_user_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favoriteNotes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='parfumuri.note'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favoritePerfumes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='parfumuri.perfume'),
        ),
    ]
