# Generated by Django 5.1.4 on 2025-01-10 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumuri', '0007_review_created_at_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('celebrityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='celebrity_images/')),
                ('description', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('perfumes', models.ManyToManyField(related_name='worn_by_celebrities', to='parfumuri.perfume')),
            ],
        ),
    ]
